### ISSUE TITLE
Post successful deployment I can only see 500 Internal server error page only.

### ISSUE THREAD

**Issue by Varunr1995** [Azure-Samples/msdocs-django-postgresql-sample-app#32]
I followed this documentation https://learn.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=django%2Cmac-linux#i-get-an-error-when-running-database-migrations to deploy my Django based web application over cloud with PostgreSql DB, everything went well and server is up and running, when I navigated to the link generated by azure page to check my website, I can only see 500 Error Page.

The same application ran perfectly in local environment without any issue, but in production environment it's failing to load the navigated urls. I tried to debug the issue but the issue still remain same.

I followed this link https://learn.microsoft.com/en-us/answers/questions/449267/500-server-error-on-django-on-app-service-when-deb?comment=question#newest-question-comment to update and check anything, but no use.

Looking forward to hear valuable inputs to resolve my issue.

Link 1 :: https://learn.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=django%2Cmac-linux#i-get-an-error-when-running-database-migrations

Link 2 :: https://learn.microsoft.com/en-us/answers/questions/449267/500-server-error-on-django-on-app-service-when-deb?comment=question#newest-question-comment

**Comment by pamelafox** [comment]
Hi Varun! I have a blog post here with some tips:
http://blog.pamelafox.org/2023/01/tips-for-debugging-django-app.html

Can you check the Log stream as advised in the post? The cause for the 500 should be in there.

**Comment by pamelafox** [comment]
@Varunr1995 Can you let me know if your issue was resolved?

**Comment by Varunr1995** [comment]
@pamelafox Yes, the issue got resolved. Thanks for your support in resolving the issue.

**Comment by EuphoriaLux** [comment]
I got the same Issue i change the 


STATICFILES_STORAGE = whitenoise.storage.CompressedManifestStaticFilesStorage

To

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

Work's now for me.

**Comment by molin6** [comment]
@EuphoriaLux Legend.
