### ISSUE TITLE
Updating/work-with this template for GHA feature.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/msdocs-django-postgresql-sample-app#52]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

We are updating this template to support new features in `Github Action`.

For the Github Action feature: We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
<img width="302" alt="image" src="https://github.com/Azure-Samples/openai-plugin-fastapi/assets/81678720/b78e7045-08c4-4e09-90cd-ba0b22f50fe7">

@rajeshkamal5050 , @pamelafox for notification.

**Comment by bobtabor-msft** [comment]
This repo does not contain the crossed out code, and though I don't completely understand the purpose of this change, it appears to make azd available in GitHub actions, and if that's the case, it appears that this repo doesn't need azd in its steps section. So, I'm going to close this. If you feel this is in error, please submit a PR to help me understand exactly what needs to happen here. Thank you.
